#!/bin/sh

# didn't work:
# clang -I`pwd`/include/smack try/pthread_vs_spthread.c

# didn't work:
#clang -iquote -I`pwd`/include/smack try/pthread_vs_spthread.c

# clang says this is not needed: -nobuildininc
clang -nostdinc -I`pwd`/include/smack -c \
      try/pthread_vs_spthread.c


